apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXdOVEEyTVRNek5Wb1hEVE16TURRd01qQTJNVE16TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTy9oCjVsTVNFOWV2Sm9pQ3RSbjhhYmp1eGc1UkxWWnVZQk9LcGN6ZVNWVm5uOWFYVzBVWmo4MVg4SmEwRHo1VG16Q3gKbVduNUFFK25DckNhS01acVhjV1ZyM1dOK3lzNTNrWDJEN0Y2WGZsejIwWXYyU0I4S0N4Z1BWVWNacUtDSVY5MwpFS3ZwVC9LN1ozbXRQMWMydEhIWEtMVExiN3k4ZWcrS2dUOFRkNmI5eU1IanlpUlEzRk1WUFhwTjNiK0xweW00Ci9QdW1NZVRiS2FhQmpSU3ZBYjZmUnJMSnpRQ1A0c3ZMSzRZN3hPbkEzUzdRZUxIVForcURwQnhzbC9uUjZCVkEKYzd5SFhWOXR2NStpVWZoQWZDYlBEbStnTWhrNkpGczNTNi9ybVkzQTdYcU02SHRFNVhZRWFZdzU0NWwybHpKSgpiZmt0U3BoMWpFTEhTcDZGYzFFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJSkJQSVlIZlRMalBZNmxYNi9kRGtTZ0hhQ1VNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnFZOWlTd2g0THczY2JxMG8vWApCTjFqcEdObmZJTW9OMEhsNTFkc3g5MC8xWXg1aG5DRU03b0tIRUNNZVdJNHp4V3lUa3MzRWxhdWFKVkEzeUFrCkRIdGxzREpQaFZ5NDJKdlI3Ym1OTGhUVys1aVJLRWNXZHRRNFQwUVhSeVNiNFFGN2IyWU9nclpHbU5udnJkbUoKTjJqOE9WaWFEbUI1V3Q0TGJmcHBiTkFoODNsdERlYlpTVVpHMCtmMnFEZEFtdGJUYkJsV0tHdHNNNFY2M0pkTApXdzNHRmNQQnlFeFRINkJKSitzY3dZTEo4Z1ZpQ2JSQkhDdHdXN2w4WkVJWVBsT2FZai9SYm1WSS9QSlgrQ1FwCmlqRDVVUFdnMTFKSmRpYS91WkxtKzFiYk5aQVpsV0ZmbElRNmVNaHBONWhiYzBtSXhpSmI2b0dOSW9iTnBab3EKc3drPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://5444269FA3AE8CF46F75B46B21E284B3.gr7.us-west-2.eks.amazonaws.com
    name: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
contexts:
  - context:
      cluster: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
      user: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
    name: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
current-context: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:us-west-2:764906212235:cluster/ovidiu-oss
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - us-west-2
          - eks
          - get-token
          - --cluster-name
          - ovidiu-oss
        command: aws
        env:
          - name: AWS_PROFILE
            value: splat-dev
